name: KIP-Backend build (.NET)

on:
  push:
    branches: [ master, KIP-feature/v1.0, release/v1.0 ]
  pull_request:
    branches: [ master, KIP-feature/v1.0, release/v1.0 ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true
    
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Codecov
      uses: codecov/codecov-action@v1.5.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ./coverage1.xml,./coverage2.xml # optional
        flags: unittests # optional