name: KIP-Backend build (.NET)

on:
  push:
    branches: [ master, KIP-feature/v1.0, release/v1.0 ]
  pull_request:
    branches: [ master, KIP-feature/v1.0, release/v1.0 ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true
    - name: Run tests with coverage
      run: dotnet test --no-build --collect:"XPlat Code Coverage"
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@4.8.5
      with:
        reports: '*Test*/TestResults/*/coverage.cobertura.xml'
        targetdir: 'CoverageReports'
        reporttypes: 'HtmlInline;Cobertura'
        verbosity: 'Verbose'
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: CoverageReports # Artifact name        
        path: CoverageReports # Directory containing files to upload

  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Codecov
      uses: codecov/codecov-action@v1.5.2
      with:
        files: ./coverage1.xml,./coverage2.xml # optional
        flags: unittests # optional